- name: Add New User
  user:
    name: "{{ user }}"
    shell: /bin/bash
  tags: 
  - add_user
  - never

- name: Grant SSH access
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '../../public-keys/{{ ssh_user }}/{{ssh_user}}.id_rsa.pub') }}"
  tags:
  - always
